# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: flow_spot_development

test:
  <<: *default
  database: flow_spot_test

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
